UnitedCaseStudy.Web/Models/ErrorViewModel.cs
namespace UnitedCaseStudy.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UnitedCaseStudy.Web/Controllers/NoteController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using RestSharp;
using UnitedCaseStudy.Entity.Entities;
using Microsoft.Extensions.Configuration;
using UnitedCaseStudy.Data.Abstract;
using UnitedCaseStudy.Web.Services;

namespace UnitedCaseStudy.Web.Controllers
{
    public class NoteController : Controller
    {
        private readonly IRestService _restService;
        public NoteController( IRestService restService)
        {
            _restService = restService;
        }

        public IActionResult Index()
        {
          var result= _restService.RestGetAllMethod("GetAllNotes");
            if (!string.IsNullOrEmpty(result))
            {
                var model=JsonConvert.DeserializeObject<List<Note>>(result).Where(x => x.IsDeleted == false && x.ParentNoteId == null).ToList();
                return View(model);
            }
            else
            {
                return View(new List<Note>());
            }
        }

        [HttpGet("Note/Index/ParentNoteId{id:int}")]
        public IActionResult Index(int id)
        {
            ViewBag.ParentNoteId = id;
            var parentNotes = _restService.RestGetAllMethod("GetAllNotes");
            var notes = JsonConvert.DeserializeObject<List<Note>>(parentNotes).Where(x => x.ParentNoteId == id).ToList();
            //if (notes.Count>0)
            return View(notes);

        }

        [HttpGet("Note/Update/{id:int}")]
        public IActionResult Update(int id)
        {
            var allNotes = _restService.RestGetAllMethod("GetAllNotes");
            var notes = JsonConvert.DeserializeObject<List<Note>>(allNotes).Where(x => x.Id == id).FirstOrDefault();
            return View(notes);
        }

        [HttpPost]
        public IActionResult Update(Note model)
        {
            var result = _restService.RestUpdateMethod("UpdateNote", JsonConvert.SerializeObject(model));
            if (!string.IsNullOrEmpty(result)) { 
                var updateNote = JsonConvert.DeserializeObject<Note>(result);
                if (updateNote.ParentNoteId != null && updateNote.ParentNoteId > 0)
                    return RedirectToAction("Index", new { id = updateNote.ParentNoteId });
                else
                    return RedirectToAction("Index");
            }
            else
                return View(model);
        }
  
        public IActionResult Create(int? id)
        {
            Note model = new Note();
            model.ParentNoteId=id;
            return View(model);
        }

        [HttpPost]
        public IActionResult Create(Note model)
        {
            if (_restService.RestCreateMethod("CreateNote", JsonConvert.SerializeObject(model)))
            {
                if(model.ParentNoteId!=null&&model.ParentNoteId>0)
                    return RedirectToAction("Index", new { id = model.ParentNoteId });
                else
                    return RedirectToAction("Index");
            }
                
            else
                return View(model);
        }

        [HttpGet("Note/Delete/{id:int}")]
        public IActionResult Delete(Note model)
        {
            if (_restService.RestDeleteMethod("DeleteNote", JsonConvert.SerializeObject(model)))
                return RedirectToAction("Index");
            else
                return View(model);
        }
    
    }
}

UnitedCaseStudy.Web/Views/Note/Create.cshtml
@model Note

<div class="container">
    <div class="card">
        <div class="card-body">
            <form asp-controller="Note" asp-action="Create" method="post">
                
                <div class="form-group row">
                    <div class="col-md-6">
                        <label class="control-label">Not</label>
                        <input class="form-control" asp-for="NoteText" required />
                    </div>
                    <input type="hidden" id="ParentNoteId" name="ParentNoteId" value="@Model.ParentNoteId" />
                    <input type="hidden" id="IsDeleted" name="IsDeleted" value="@Model.IsDeleted=false" />
                </div>
           
                <div class="row form-group">
                    <div class="col-lg-12">
                        <input type="submit" class="btn btn-primary" value="Kaydet" style="float: right;" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

UnitedCaseStudy.Web/Views/Note/Index.cshtml
@model List<Note>
@{
    string ParentNoteId = "";
    if (ViewBag.ParentNoteId!=null)
    {
        ParentNoteId = ViewBag.ParentNoteId.ToString();
    }
}
<div class="row form-group">
    <div class="col-lg-12">
        <a href="/Note/Create@(!string.IsNullOrEmpty(ParentNoteId)? "/"+ParentNoteId : "")" class="btn btn-primary" style="float: right;">Ekle</a>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <table class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <td>Id</td>
                        <td>NoteText</td>
                        <td></td>
                        <td></td>
                        <td></td>
                    </tr>
                </thead>
                <tbody>
                    @{
                        if (Model != null && Model.Count > 0)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>@item.Id</td>
                                    <td>@item.NoteText</td>
                                    <td width="125px"><a asp-action="Update" asp-route-id="@item.Id" class="btn btn-primary"><i class="la la-pencil"></i> Düzenle</a></td>
                                    <td width="125px"><a asp-action="Index" asp-route-id="@item.Id" class="btn btn-secondary"><i class="la la-pencil"></i> Alt Notlar</a></td>
                                    <td width="125px"><a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"><i class="la la-pencil"></i> Sil</a></td>
                                </tr>
                            }
                        }
                        else
                        {

                        }
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

UnitedCaseStudy.Web/Views/Note/Update.cshtml
@model Note

<div class="container">
    <div class="card">
        <div class="card-body">
            <form asp-controller="Note" asp-action="Update" method="post">
                <input type="hidden" id="Id" name="Id" value="@Model.Id" />
                <div class="card-body">
                    <div class="row form-group">
                        <div class="col-md-6">
                            <label class="control-label"> Not</label>
                            <input class="form-control" asp-for="NoteText" />
                            <span asp-validation-for="NoteText" class="text-danger"></span>
                        </div>
                      
                      

                        <div class="row form-group">
                        <div class="col-lg-12">
                            <input type="submit" class="btn btn-primary" value="Güncelle" style="float: right;" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

UnitedCaseStudy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - UnitedCaseStudy.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/UnitedCaseStudy.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">UnitedCaseStudy.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - UnitedCaseStudy.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>